server:
  port: 8080
spring:
  application:
    name: resto-app
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
base.url: https://6020d6d046f1e4001780370b.mockapi.io/govtech/api/v1