server:
  port: 8762
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: resto-gateway
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  sensitive-headers:
  routes:
    resto-app:
      path: /api/app/**
      url: http://localhost:8080
      serviceId: resto-app
    resto-transaction:
      path: /api/transaction/**
      url: http://localhost:8081
      serviceId: resto-transaction
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: false
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
myusers-service:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100